services:
  ollama:
    volumes:
      - ollama:/root/.ollama
      - ./scripts/ollama.sh:/entrypoint.sh
    environment:
      - MODELS_BASE=${MODELS_BASE}
      - OLLAMA_HOST=0.0.0.0
      # CPU Threading options - adjust based on your CPU cores
      - OLLAMA_CPU_THREADS=${CPU_THREADS:-4}
      - OLLAMA_GPU_LAYERS=${GPU_LAYERS:-24}
      # Memory and batch size
      - OLLAMA_NUMA=true           # Enable NUMA support
      - OLLAMA_BATCH_SIZE=${BATCH_SIZE:-2048}
      # Cache settings
      - OLLAMA_MMAP=true           # Enable memory mapping
      - OLLAMA_CACHE_SIZE=${CACHE_SIZE:-3072}
    container_name: ollama
    ports:
      - "11434:11434"
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:latest
    entrypoint: ["/usr/bin/bash", "/entrypoint.sh"]
    deploy:
      resources:
        limits:
          memory: ${OLLAMA_MEMORY_LIMIT:-8g}
        reservations:
          devices:
            - capabilities: [gpu]

  open-webui:
    image: ghcr.io/open-webui/open-webui:latest
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
      - open-webui-data:/app/data
      - ./scripts/openwebui.sh:/app/backend/openwebui.sh
    environment:
      - DATA_DIR=/app/data
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost:5432/${POSTGRES_DATABASE}
      - NVIDIA_VISIBLE_DEVICES=all
      - WEBUI_NAME=AIXCL
      - OLLAMA_BASE_URL=http://localhost:11434
      - OPENWEBUI_EMAIL=${OPENWEBUI_EMAIL}
      - OPENWEBUI_PASSWORD=${OPENWEBUI_PASSWORD}
      # WebUI Performance settings
      - WEBUI_CONCURRENCY=4        # Reduced concurrency for balanced performance
      - WEBUI_THREADS=2            # Conservative thread count
      # Add error reporting and logging
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - ENABLE_TELEMETRY=${ENABLE_TELEMETRY:-false}
    extra_hosts:
       - "host.docker.internal:host-gateway"
    depends_on:
      - postgres
      - ollama
    network_mode: host
    restart: always
    command: ["/bin/bash", "-c", "chmod +x openwebui.sh && bash openwebui.sh"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health", "||", "exit", "1"]
      start_period: 30s
      interval: 30s
      timeout: 10s
      retries: 3

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DATABASE
      # Add connection tuning
      - POSTGRES_MAX_CONNECTIONS=${PG_MAX_CONNECTIONS:-100}
      - POSTGRES_SHARED_BUFFERS=${PG_SHARED_BUFFERS:-128MB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - postgres-backups:/backups
    network_mode: host
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]  # Check if PostgreSQL is ready
      interval: 30s
      timeout: 10s
      retries: 3
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: $PGADMIN_EMAIL
      PGADMIN_DEFAULT_PASSWORD: $PGADMIN_PASSWORD
      PGADMIN_LISTEN_PORT: 5050
    network_mode: host
    depends_on:
      - postgres
    restart: always

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: open-webui
    restart: always

volumes:
  ollama:
  open-webui:
  open-webui-data:
  postgres-data:
  postgres-backups:

networks:
  ollama-network:
    driver: bridge
