services:
  open-webui:
    ports:
      - "8080:8080"
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
    networks:
      - ollama-network

  ollama:
    ports:
      - "11434:11434"
    networks:
      - ollama-network

networks:
  ollama-network:
    driver: bridge